### ISSUE TITLE
icons arent positions correctly

### ISSUE THREAD

**Issue by evilytwisted** [Botspot/Windows-10#10]
the icons arent aligned to the right there almost in the center
![2021-03-17-141245_1280x720_scrot](https://user-images.githubusercontent.com/3299466/111524791-de20cd80-872a-11eb-9e0f-0a020e1b330d.png)
is there anyway to make the icons be at the far right?

**Comment by Botspot** [comment]
Did you mean this icon?
![111524791-de20cd80-872a-11eb-9e0f-0a020e1b330d](https://user-images.githubusercontent.com/54716352/111525632-d4e43080-872b-11eb-9217-44b0de23943e.png)

**Comment by evilytwisted** [comment]
Yes

**Comment by Botspot** [comment]
To fix that, go to menu -> Preferences -> Tint2 settings.  
Click `Edit Theme` on the top.  
Click the `Panel` tab on the right.  
Find the `Length` setting and change the percentage until it fits your screen size. Hit apply to refresh the tint2 panel to see how it looks.  
Click OK on both windows to finish.

If you have a small screen, you will only have to change the percentage a little bit or none at all. But if you have a large screen, it'll have to change quite a bit.

By default, Windows 10 theme uses a fairly low percentage in order to be usable on small screens. But for larger ones, the default percentage is sub-optimal. Fortunately, it's easy to fix! :)

**Comment by evilytwisted** [comment]
thank you for the suggestion,  and it indeed fixed the issue.
[image: cloudHQ] <https://www.free-email-tracker.com> Powered by
cloudHQ <https://www.free-email-tracker.com>
